name = "hex-gram-schmidt"
defaultTargets = ["HexGramSchmidt"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexMatrix"
git = "https://github.com/kim-em/hex-matrix.git"
rev = "7359d9c53c3d85309b526dd1663a33b28a28bf50"

[[require]]
name = "HexRowReduce"
git = "https://github.com/kim-em/hex-row-reduce.git"
rev = "48a6d92ac69e1fd6b3b1a86be9cb793a76e000c2"

[[require]]
name = "HexDeterminant"
git = "https://github.com/kim-em/hex-determinant.git"
rev = "8ce401452f1cfcf714d46887440d7d4341177818"

[[require]]
name = "HexBareiss"
git = "https://github.com/kim-em/hex-bareiss.git"
rev = "733e2937905ad612423d86a2e39d345fd72ed8ac"

[[lean_lib]]
name = "HexGramSchmidt"
