name = "hex-gram-schmidt"
defaultTargets = ["HexGramSchmidt"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexMatrix"
git = "https://github.com/kim-em/hex-matrix.git"
rev = "972c81f44503301ec8c65f788d4487491dc3f6cc"

[[require]]
name = "HexRowReduce"
git = "https://github.com/kim-em/hex-row-reduce.git"
rev = "922d066445a6a9e2deb2cad5cca099b2dad2c98e"

[[require]]
name = "HexDeterminant"
git = "https://github.com/kim-em/hex-determinant.git"
rev = "0afc5bac5033aeb453fc873dcf043e216011a72e"

[[require]]
name = "HexBareiss"
git = "https://github.com/kim-em/hex-bareiss.git"
rev = "93f03da23452d0bb0f3848d10bfd8d40cca88936"

[[lean_lib]]
name = "HexGramSchmidt"
